# If a config.py file exists, this file is ignored unless it's explicitly loaded
# via config.load_autoconfig(). For more information, see:
# https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#loading-autoconfigyml
# DO NOT edit this file by hand, qutebrowser will overwrite it.
# Instead, create a config.py - see :help for details.
config.load_autoconfig()

c.tabs.background = True
c.new_instance_open_target = 'window'
#c.url.start_pages('https://www.google.com')
c.downloads.position = 'bottom'
#c.spellcheck.languages = ['en-US']
# Fonts
c.fonts.prompts = '12pt "MesloLGS NF"'
c.fonts.statusbar = '12pt "MesloLGS NF"'
c.fonts.completion.entry = '12pt "MesloLGS NF"'

# Keybinds
config.bind('M','hint links spawn --detach mpv {hint-url}')
config.bind('St','hint links spawn --detach streamlink {hint-url} best')
config.bind('Y','hint links spawn alacritty -e yt-dlp {hint-url}')
config.bind('ce', 'config-edit')
config.bind('B', 'spawn --userscript qute-bitwarden')

config.bind('<Shift-Left>', 'back')
config.bind('<Shift-Down>', 'tab-prev')
config.bind('<Shift-Up>', 'tab-next')
config.bind('<Shift-Right>', 'forward')


# Editor
c.editor.command = ['emacs', '{}']

# Colorscheme
config.source('gruvbox.py')
