#!/bin/bash

# Simple bash script with ffmpeg to convert any audiofile to mp3 and add artist+title metadata
# made for SoundCloud files downloaded with yt-dlp/youtube-dl
# Usage: metadata-fix "Artist name" "input file format"

mkdir temp
for x in *.$2; do
    mv "$x" "./temp/${x% [*}.$2"
done

cd temp

for y in *.$2; do
    ffmpeg -i "$y" -acodec libmp3lame -metadata artist="$1" -metadata title="${y%.$2*}" "../${y%.$2*}.mp3" # Convert to mp3
done
cd ..
rm -r temp
