#!/bin/bash

while getopts ":hrlpf" option; do
   case $option in
      h)  # help
        echo "Usage:"
        echo "-h - displays list of possible arguments"
        echo "-r - plays random tracks from all subfolders of ~/Music"
        echo "-l - lists all subfolders of ~/Music"
        echo "-p - plays tracks from selected folder example: music -p \"Some_album\""
        exit;;
      r)  # play random track
        find ~/Music/**/*.mp3 | mpv --playlist=- --shuffle --no-audio-display
#        mpv $HOME/Music/*/* --shuffle --no-audio-display
        exit;;
      l)  # list folders in user/Music folder
        #exa -l $HOME/Music
        arrVar=()
        for i in ~/Music/*
        do
          arrVar+=("$i")
        done
        arrElement=0
        for value in "${arrVar[@]}"
        do
          echo "[$arrElement] ${value##*/}" # List every directory in ~/Music without absolute path
          let "arrElement+=1" # Increment listed element value
        done
        echo Select listed folder [x]
        read selection # Selection variable number of a directory in a list
        mpv "${arrVar[$selection]}"/* --no-audio-display 
        exit;;
      p)  # play from folder
        mpv $HOME/Music/"$2"/* --shuffle --no-audio-display
        exit;;
      f)
        mpv "$(find $HOME/Music/* -type d | fzf -m)" #  Select folders from Music directory
        exit;;
      \?) # Option not supported
        echo "Argument not supported find all supported arguments with -h"
        exit;;
   esac
done
